config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors
  devise_for :patients

  root 'splash#index'

  namespace :patients do
    get "profile" => "patients#profile", as: "profile"
    get "edit_profile" => "patients#edit_profile", as: "edit_profile"
    put "update_profile" => "patients#update_profile"

    get "doctor/:id" => "patients#view_doctor", as: "doctor_profile"
    post "make_appointment_with/:id" => "patients#create_appointment"
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients/base_patients_controller.rb
class Patients::BasePatientsController < ApplicationController
  #before_action :validate_admin

  def validate_admin
    unless current_admin
      render "errors/401", status: :unauthorized
    end
  end


  def index
  end
end

app/controllers/patients/patients_controller.rb
class Patients::PatientsController < Patients::BasePatientsController
  before_action :load_patient
  before_action :load_doctor, only: [:view_doctor, :create_appointment]
  def profile
  end

  def edit_profile
  end

  def update_profile
    if @patient.update_attributes(allowed_params)
      redirect_to patients_profile_path, notice: "Profile updated sucessfully"
    else
      render :edit_profile
    end
  end

  def view_doctor
    @appointment = Appointment.new
  end

  def create_appointment
    @appointment = Appointment.new(appointment_params)
    @appointment.doctor = @doctor
    @appointment.patient = @patient

    @appointment.save
    render :view_doctor
  end

  private
  def load_patient
    @patient = current_patient
  end

  def load_doctor
    @doctor = Doctor.find(params[:id])
  end

  def allowed_params
    params.require(:patient).permit(
    :name, :birthdate,
    :bloodgroup, :tb, :cigarettes, :drug_use,
    :hiv, :bmi, :height, :diabetes, :medication_history, :medical_history)
  end

  def appointment_params
    params.require(:appointment).permit(:appointment_date)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    @doctors = Doctor.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>HealtHCare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
</style>
<body>

<!-- Navbar -->
<div class="w3-top">
<ul class="w3-navbar w3-black w3-card-2 w3-left-align">
  <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
    <a class="w3-padding-large" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
  </li>
  <li><a href="/" class="w3-hover-none w3-hover-text-grey w3-padding-large">HOME</a></li>
  <% if current_patient %>
  <li><%= link_to "profile", patients_profile_path, class: "w3-hover-none w3-hover-text-grey w3-padding-large" %></li>
  <% end %>
  <li class="w3-hide-small w3-dropdown-hover">
    <a href="javascript:void(0)" class="w3-hover-none w3-padding-large" title="More">MORE <i class="fa fa-caret-down"></i></a>
    <div class="w3-dropdown-content w3-white w3-card-4">
      <a href="/">Stuff</a>
      <a href="/">In</a>
      <a href="/">Dropdown</a>
    </div>
  </li>
  <% if current_patient
    a = link_to 'Logout', destroy_patient_session_path, method: :delete, class: "w3-padding-large w3-hover-red"
  else
    a = link_to "sign in", new_patient_session_path, class: "w3-padding-large w3-hover-red"
  end

  %>

  <li class="w3-hide-small w3-right"><%= a %></li>
</ul>
</div>

<!-- Navbar on small screens -->
<div id="navDemo" class="w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">
  <ul class="w3-navbar w3-left-align w3-black">
    <li><a class="w3-padding-large" href="#FIXME">example navbar item</a></li>
  </ul>
</div>

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">
  <div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="band">
    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
    <p><%= yield %></p>
  </div>

</div>


<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge">
  <i class="fa fa-facebook-official w3-hover-text-indigo"></i>
  <i class="fa fa-instagram w3-hover-text-purple"></i>
  <i class="fa fa-snapchat w3-hover-text-yellow"></i>
  <i class="fa fa-pinterest-p w3-hover-text-red"></i>
  <i class="fa fa-twitter w3-hover-text-light-blue"></i>
  <i class="fa fa-linkedin w3-hover-text-indigo"></i>
  <p class="w3-medium">Powered by <a href="http://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

</body>
</html>

app/views/patients/patients/_summary.html.erb
<h3>Personal</h3>
<p><b>Name:</b> <%= patient.name %> | <%= patient.birthdate %></p>
<p><b>Height:</b> <%= patient.height %>, <b>BMI</b> <%= patient.bmi %></p>
<p><b>Bloodgroup:</b> <%= patient.bloodgroup %></p>
<h3>Medical</h3>
<table>
<tr>
  <td class = "label"><b>TB</b></td>
  <td><%= patient.tb %></td>
  <td class = "label"><b>HIV</b></td>
  <td><%= patient.hiv %></td>
</tr>
<tr>
  <td class = "label"><b>Smoke cigarettes?</b></td>
  <td><%= patient.cigarettes %></td>
  <td class = "label"><b>Diabetes?</b></td>
  <td><%= patient.diabetes %></td>
</tr>
</table>
<p><b>Drug Use:</b> <%= simple_format patient.drug_use %></p>

<p><b>Medication History</b> <%= simple_format patient.medication_history %> </p>
<p><b>Medical History</b> <%= simple_format patient.medical_history %></p>

app/views/patients/patients/edit_profile.html.erb
<%= form_for @patient, url: {action: :update_profile}, method: :put  do |f| %>
<% if @patient.errors.any? %>
<div id = "error_explanation">
  <h2><%= pluralize(@patient.errors.count, "error") %> prohibited your profile from being saved: </h2>
  <ul>
    <% @patient.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<fieldset>
  <legend>Contact</legend>
<div class="field">
  <%= f.label :name, "Full Legal Name" %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <p>Email: <%= @patient.email %>.  <%= link_to "Change email or password", edit_patient_registration_path %></p>
</div>
</fieldset>
<fieldset>
  <legend>Personal</legend>
<div class = "field">
  <%= f.label :birthdate %>&nbsp;
  <%= f.date_select :birthdate %>
</div>

<div class="field">
  <%= f.label :height %><br />
  <%= f.text_field :height %>
</div>

<div class="field">
  <%= f.label :bmi %><br />
  <%= f.text_field :bmi %>
</div>

<div class = "field">
  <%= f.label :bloodgroup %><br />
  <%= f.text_field :bloodgroup %>
</div>
</fieldset>
<fieldset>
  <legend>Medical</legend>
  <%= f.check_box :tb %> <%= f.label :tb, "Do you have TB?" %>  <br />
  <%= f.check_box :cigarettes %> <%= f.label :cigarettes, "Do you smoke cigarettes?" %> <br />
  <%= f.check_box :hiv %> <%= f.label :hiv, "Do you have HIV?" %> <br />
  <%= f.check_box :diabetes %> <%= f.label :diabetes, "Do you have diabetes?" %> <br />

  <p><%= f.label :drug_use %><br />
  <%= f.text_area :drug_use %></p>
  <p><%= f.label :medical_history %><br />
  <%= f.text_area :medical_history %></p>
  <p><%= f.label :medication_history %><br />
  <%= f.text_area :medication_history %></p>
  <!--Your resume will automatically be added to any applications you submit.
  < % if @candidate.resume.path %>
  You can upload a new copy of your resume by selecting a file. < %= link_to "Resume on file", document_path(@candidate.resume) %>
  < % end %>
  < %= f.file_field :resume %>-->
</fieldset>


<%= f.submit "Update Profile" %>
<% end %>

app/views/patients/patients/profile.html.erb
Something change?  Click <%= link_to "here", patients_edit_profile_path %> to update your profile information.

<%= render partial: "summary", locals: {patient: @patient} %>

app/views/patients/patients/view_doctor.html.erb
<h3>Doctor's profile</h3>
<%= @doctor.email %>
<p>
<% if @doctor.appointments.any? %>
  <% @doctor.appointments.each do |a| %>
    Appointment on <%= a.appointment_date %> with <%= a.patient.email %><br />
  <% end %>
<% end %>
</p>

<%= form_for @appointment, url: {action: :create_appointment}, method: :post do |f| %>
<p>Make an appointment: <%= f.datetime_select :appointment_date %></p>
<%= f.submit %>
<% end %>

app/views/splash/contact.html.erb
<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
  <h2 class="w3-wide w3-center">CONTACT</h2>
  <p class="w3-opacity w3-center"><i>Drop a line</i></p>
  <div class="w3-row w3-padding-32">
    <div class="w3-col m6 w3-large w3-margin-bottom">
      <i class="fa fa-map-marker" style="width:30px"></i>LOCATION<br>
      <i class="fa fa-phone" style="width:30px"></i> Phone: ##########<br>
      <i class="fa fa-envelope" style="width:30px"> </i> Email: example@example.com<br>
    </div>
    <div class="w3-col m6">
      <form action="form.asp" target="_blank">
        <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
          <div class="w3-half">
            <input class="w3-input w3-border" type="text" placeholder="Name" required name="Name">
          </div>
          <div class="w3-half">
            <input class="w3-input w3-border" type="text" placeholder="Email" required name="Email">
          </div>
        </div>
        <input class="w3-input w3-border" type="text" placeholder="Message" required name="Message">
        <button class="w3-btn w3-section w3-right" type="submit">SEND</button>
      </form>
    </div>
  </div>
</div>

app/views/splash/index.html.erb
  <h2 class="w3-wide">healtHCare</h2>
  <p>Connect with doctors.</p>

  <!-- %= link_to "Sign up a new doctor", new_doctor_registration_path % -->
<% if current_patient %>
<h3>List of Doctors</h3>
<% @doctors.each do |d| %>
  <p>See <%= link_to d.email, patients_doctor_profile_path(d) %> profile to make an appointment.</p>
<% end %>
<% end %>